---
- name: Install Nginx
  hosts: ec2
  become: yes
  tasks:
    - name: Install Nginx on Remote EC2
      yum:
        name: nginx
        state: present

    - name: Start Nginx 
      service:
        name: nginx
        state: started
        enabled: yes
